Metrics/AbcSize:
  Max: 18

Metrics/ClassLength:
  Max: 130

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Max: 215

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Lint/Void:
  Enabled: false
