inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 215

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
    - bin/🎉

Style/SpecialGlobalVars:
  Enabled: false

Lint/Void:
  Enabled: false
